%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/Ben/Dropbox/UMICH/Corvia/Corvia/data R01 rebuttal 2020-09-02.xlsx
%    Worksheet: Blad1
%
% Auto-generated by MATLAB on 15-Sep-2021 09:58:08

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 75);

% Specify sheet and range
opts.Sheet = "Blad1";
opts.DataRange = "A2:BW15";

% Specify column names and types
opts.VariableNames = ["VarName1", "gender", "age", "bodyweight", "height", "bodymassindex", "reportedcardiovascularcomorbidity", "VarName8", "PCrATP", "TR", "T1PCr", "T1gATP", "partialsaturationcorrectionfactor", "correctedPCrATP", "VarName15", "VarName16", "tCr", "HMRSestimated", "biopsyestimated", "conversionfactor", "tCrestimated", "VarName22", "VarName23", ...
    "HR", "LVEDV", "LVESV", "LVSV", "LVEF", "LVCO", "LVmass", "RVEDV", "RVESV", "RVSV", "RVEF", "RVCO", "septalT1", "septalT2", ...
    "VarName38", "VarName39", ...
    "systemicsystolicbloodpressure", "systemicdiastolicbloodpressure", "heartrate", "systolicrightatrialpressure", "diastolicrightatrialpressure", "systolicrightventriclepressure", "diastolicrightventricularpressure", "systolicpulmonaryarterypressure", "diastolicpulmonaryarterypressure", "pulmonarycapillarywedgepressure", "CO", "SV", ...
    "systemicsystolicbloodpressure1", "systemicdiastolicbloodpressure1", "heartrate1", "systolicrightatrialpressure1", "diastolicrightatrialpressure1", "systolicrightventriclepressure1", "diastolicrightventricularpressure1", "systolicpulmonaryarterypressure1", "diastolicpulmonaryarterypressure1", "pulmonarycapillarywedgepressure1", "CO1", "SV1", ...
    "exerciseintensity", "systemicsystolicbloodpressure2", "systemicdiastolicbloodpressure2", "heartrate2", "systolicrightatrialpressure2", "diastolicrightatrialpressure2", "systolicrightventriclepressure2", "diastolicrightventricularpressure2", "systolicpulmonaryarterypressure2", "diastolicpulmonaryarterypressure2", "pulmonarycapillarywedgepressure2", "CO2"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double", "double", "string", "string", "double", "double", "double", "double", "double", "double", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "double", "string", "string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double"];

% Specify variable properties
opts = setvaropts(opts, ["reportedcardiovascularcomorbidity", "VarName8", "VarName15", "VarName16", "VarName38", "VarName39", "systemicsystolicbloodpressure", "systemicdiastolicbloodpressure", "systolicrightatrialpressure", "diastolicrightatrialpressure", "systolicrightventriclepressure", "diastolicrightventricularpressure", "exerciseintensity", "pulmonarycapillarywedgepressure2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["gender", "reportedcardiovascularcomorbidity", "VarName8", "VarName15", "VarName16", "VarName38", "VarName39", "systemicsystolicbloodpressure", "systemicdiastolicbloodpressure", "systolicrightatrialpressure", "diastolicrightatrialpressure", "systolicrightventriclepressure", "diastolicrightventricularpressure", "exerciseintensity", "pulmonarycapillarywedgepressure2"], "EmptyFieldRule", "auto");

% Import the data
dataR01rebuttal20200902 = readtable("/Users/Ben/Dropbox/UMICH/Corvia/Corvia/data R01 rebuttal 2020-09-02.xlsx", opts, "UseExcel", false);

Otdata  = table2struct(dataR01rebuttal20200902); 

f = fieldnames(Otdata); 
v = struct2cell(Otdata); 

f{strcmp('VarName1',f)}   = 'index'; 
f{strcmp('bodyweight',f)} = 'weight'; 
f{strcmp('bodymassindex',f)} = 'BMI'; 
f{strcmp('HR',f)} = 'HR_MRI'; 
f{strcmp('LVCO',f)} = 'LVCO_MRI';
f{strcmp('RVCO',f)} = 'RVCO_MRI'; 

f{strcmp('systemicsystolicbloodpressure',f)} = 'P_SAs'; 
f{strcmp('systemicdiastolicbloodpressure',f)} = 'P_SAd'; 
f{strcmp('heartrate',f)} = 'HR_RHC'; 
f{strcmp('systolicrightatrialpressure',f)} = 'P_RAs'; 
f{strcmp('diastolicrightatrialpressure',f)} = 'P_RAd'; 
f{strcmp('systolicrightventriclepressure',f)} = 'P_RVs'; 
f{strcmp('diastolicrightventricularpressure',f)} = 'P_RVd'; 
f{strcmp('systolicpulmonaryarterypressure',f)} = 'P_PAs'; 
f{strcmp('diastolicpulmonaryarterypressure',f)} = 'P_PAd'; 
f{strcmp('pulmonarycapillarywedgepressure',f)} = 'PCWP'; 
f{strcmp('CO',f)} = 'CO_RHC'; 
f{strcmp('SV',f)} = 'SV'; 

f{strcmp('systemicsystolicbloodpressure1',f)} = 'P_SAs_20'; 
f{strcmp('systemicdiastolicbloodpressure1',f)} = 'P_SAd_20'; 
f{strcmp('heartrate1',f)} = 'HR_RHC_20'; 
f{strcmp('systolicrightatrialpressure1',f)} = 'P_RAs_20'; 
f{strcmp('diastolicrightatrialpressure1',f)} = 'P_RAd_20'; 
f{strcmp('systolicrightventriclepressure1',f)} = 'P_RVs_20'; 
f{strcmp('diastolicrightventricularpressure1',f)} = 'P_RVd_20'; 
f{strcmp('systolicpulmonaryarterypressure1',f)} = 'P_PAs_20'; 
f{strcmp('diastolicpulmonaryarterypressure1',f)} = 'P_PAd_20'; 
f{strcmp('pulmonarycapillarywedgepressure1',f)} = 'PCWP_20'; 
f{strcmp('CO1',f)} = 'CO_RHC_20'; 
f{strcmp('SV1',f)} = 'SV_20'; 

f{strcmp('systemicsystolicbloodpressure2',f)} = 'P_SAs_max'; 
f{strcmp('systemicdiastolicbloodpressure2',f)} = 'P_SAd_max'; 
f{strcmp('heartrate2',f)} = 'HR_RHC_max'; 
f{strcmp('systolicrightatrialpressure2',f)} = 'P_RAs_max'; 
f{strcmp('diastolicrightatrialpressure2',f)} = 'P_RAd_max'; 
f{strcmp('systolicrightventriclepressure2',f)} = 'P_RVs_max'; 
f{strcmp('diastolicrightventricularpressure2',f)} = 'P_RVd_max'; 
f{strcmp('systolicpulmonaryarterypressure2',f)} = 'P_PAs_max'; 
f{strcmp('diastolicpulmonaryarterypressure2',f)} = 'P_PAd_max'; 
f{strcmp('pulmonarycapillarywedgepressure2',f)} = 'PCWP_max'; 
f{strcmp('CO2',f)} = 'CO_RHC_max'; 


Otdata = cell2struct(v,f); 
Otdata = rmfield(Otdata,{'VarName8','VarName15','VarName16','VarName22','VarName23','VarName38','VarName39'}); 
disp(Otdata)

save Otdata.mat Otdata 


%% Clear temporary variables
clear opts